export enum TaskElementActions {
  INCREASE = "INCREASE",
  DECREASE = "DECREASE",
  EDIT = "EDIT",
  OPEN = "OPEN",
  CLOSE = "CLOSE",
  SET_POSITION = "SET_POSITION",
  OPEN_EDIT_MODE = "OPEN_EDIT_MODE",
  CLOSE_EDIT_MODE = "CLOSE_EDIT_MODE",
}
